name: Main CI workflow
on: [push, pull_request]
jobs:
  test: 
    uses: "./.github/workflows/test.yml"
    secrets:
      db_host: ${{ secrets.TEST_DB_HOST }}
      db_name: ${{ secrets.TEST_DB_NAME }}
      db_user: ${{ secrets.TEST_DB_USER }}
      db_pass: ${{ secrets.TEST_DB_PASS }}
      db_port: ${{ secrets.TEST_DB_PORT }}
  build:
    needs: test
    uses: "./.github/workflows/build-push.yml"
