name: Main CI workflow
on: [push, pull_request]
jobs:
  test:
    uses: "./.github/workflows/test.yml"
    secrets:
      db_host: ${{ secrets.TEST_DB_HOST }}
      db_name: ${{ secrets.TEST_DB_NAME }}
      db_user: ${{ secrets.TEST_DB_USER }}
      db_pass: ${{ secrets.TEST_DB_PASS }}
      db_port: ${{ secrets.TEST_DB_PORT }}
  build:
    if: github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags')
    needs: test
    uses: "./.github/workflows/build-push.yml"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
