name: Main CI workflow
on: workflow_call
jobs:
  test: 
    uses: "${{ github.repository }}/.github/workflows/test.yml@latest"
  build:
    needs: test
    uses: "${{ github.repository }}/.github/workflows/build-push.yml@latest"
