name: Test the code
on: 
  workflow_call:
    secrets:
      db_host:
        required: true
      db_port:
        required: true
      db_user:
        required: true
      db_pass:
        required: true
      db_name:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: make test DB_HOST=${{ secrets.db_host }} DB_USER=${{ secrets.db_user }} DB_PASS=${{ secrets.db_pass }} DB_NAME=${{ secrets.db_name }} DB_PORT=${{ secrets.db_port}}
